# Generated by Django 4.1.3 on 2022-12-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="part",
            field=models.CharField(
                choices=[("BE", "BackEnd"), ("FE", "FrontEnd")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("Team", "Teample"),
                    ("FMN", "Forget Me Not"),
                    ("PF", "Pre:Folio"),
                    ("DM", "diaMEtes"),
                    ("RE", "recipeasy"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
