# Generated by Django 3.0.8 on 2022-12-20 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevote',
            name='userPk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CandidateVoteUserPk', to=settings.AUTH_USER_MODEL),
        ),
    ]
