# Generated by Django 4.1.3 on 2022-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_part_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=256, unique=True, verbose_name="사용자 이메일"
            ),
        ),
    ]
