# Generated by Django 4.1.3 on 2022-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="part",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(default="", max_length=30),
        ),
    ]
